/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BuilderNewRouteImport } from './routes/builder-new'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuilderNewIndexRouteImport } from './routes/builder-new/index'
import { Route as BuilderNewAppearanceRouteImport } from './routes/builder-new/appearance'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderNewRoute = BuilderNewRouteImport.update({
  id: '/builder-new',
  path: '/builder-new',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderNewIndexRoute = BuilderNewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuilderNewRoute,
} as any)
const BuilderNewAppearanceRoute = BuilderNewAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => BuilderNewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/builder-new': typeof BuilderNewRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/builder-new/appearance': typeof BuilderNewAppearanceRoute
  '/builder-new/': typeof BuilderNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/builder-new/appearance': typeof BuilderNewAppearanceRoute
  '/builder-new': typeof BuilderNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/builder-new': typeof BuilderNewRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/builder-new/appearance': typeof BuilderNewAppearanceRoute
  '/builder-new/': typeof BuilderNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/builder-new'
    | '/login'
    | '/signup'
    | '/builder-new/appearance'
    | '/builder-new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/login'
    | '/signup'
    | '/builder-new/appearance'
    | '/builder-new'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/builder-new'
    | '/login'
    | '/signup'
    | '/builder-new/appearance'
    | '/builder-new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  BuilderNewRoute: typeof BuilderNewRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder-new': {
      id: '/builder-new'
      path: '/builder-new'
      fullPath: '/builder-new'
      preLoaderRoute: typeof BuilderNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder-new/': {
      id: '/builder-new/'
      path: '/'
      fullPath: '/builder-new/'
      preLoaderRoute: typeof BuilderNewIndexRouteImport
      parentRoute: typeof BuilderNewRoute
    }
    '/builder-new/appearance': {
      id: '/builder-new/appearance'
      path: '/appearance'
      fullPath: '/builder-new/appearance'
      preLoaderRoute: typeof BuilderNewAppearanceRouteImport
      parentRoute: typeof BuilderNewRoute
    }
  }
}

interface BuilderNewRouteChildren {
  BuilderNewAppearanceRoute: typeof BuilderNewAppearanceRoute
  BuilderNewIndexRoute: typeof BuilderNewIndexRoute
}

const BuilderNewRouteChildren: BuilderNewRouteChildren = {
  BuilderNewAppearanceRoute: BuilderNewAppearanceRoute,
  BuilderNewIndexRoute: BuilderNewIndexRoute,
}

const BuilderNewRouteWithChildren = BuilderNewRoute._addFileChildren(
  BuilderNewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  BuilderNewRoute: BuilderNewRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
